name: CI/CD - TaskManagerApiAF

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/TaskManagerApiAF/TaskManagerApiAF.csproj

      - name: Build
        run: dotnet build ./src/TaskManagerApiAF/TaskManagerApiAF.csproj --configuration Release --no-restore      

     # - name: Run tests
     #  run: dotnet test ./src/TaskManagementAF.Tests/TaskManagementAF.Tests.csproj --no-build --verbosity normal

      - name: Publish project
        run: dotnet publish ./src/TaskManagerApiAF/TaskManagerApiAF.csproj -c Release -o ./publish_output

      - name: List publish output files
        run: ls -R ./publish_output

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: 'taskmanager-api-af-ac'
          package: './publish_output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
       # env:
       #   AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
